// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/Button/index":{"id":"components/Button/index","path":"components/button","parentId":"DocLayout"},"components/Icon/index":{"id":"components/Icon/index","path":"components/icon","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "E:__组件库__node_modules__dumi__dist__client__pages__404" */'E:/组件库/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'E:/组件库/dumi-root/.dumi/tmp/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "E:__组件库__node_modules__dumi__theme-default__layouts__DocLayout__index" */'E:/组件库/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'E:/组件库/dumi-root/docs/index.md')),
'components/Button/index': React.lazy(() => import(/* webpackChunkName: "Button__index.md" */'E:/组件库/dumi-root/src/Button/index.md')),
'components/Icon/index': React.lazy(() => import(/* webpackChunkName: "Icon__index.md" */'E:/组件库/dumi-root/src/Icon/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "E:__组件库__node_modules__dumi__dist__client__pages__Demo__index" */'E:/组件库/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
